version: '3'

services:
  app:
    container_name: stac-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - RELOAD=true
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    depends_on:
      - database

  database:
    container_name: stac-db
    image: kartoza/postgis:latest
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - "5432:5432"

  migration:
    image: stac-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.db.local
    command: ["./wait-for-it/wait-for-it.sh", "localhost:5432", "--", "alembic", "upgrade", "head"]
    depends_on:
      - database
