version: '3'

services:
  app-mongo:
    container_name: stac-fastapi-mongo
    image: stac-utils/stac-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8083
      - RELOAD=false
      - ENVIRONMENT=local
      - MONGO_CONN_STRING="mongodb://dev:stac@mongo:27017"
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
    ports:
      - "8083:8083"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
    depends_on:
      - mongo_db
    command:
      bash -c "./scripts/wait-for-it.sh mongo_db:27017 && python -m stac_fastapi.mongo.app"

  mongo_db:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dev"
      MONGO_INITDB_ROOT_PASSWORD: "stac"
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27018:27017"
    command: mongod

networks:
  default:
    name: stac-fastapi-network
