[tool.ruff]
line-length = 90
select = [
    "C9",
    "D1",
    "E",
    "F",
    "W",
]

[tool.ruff.per-file-ignores]
"**/tests/**/*.py" = ["D1"]

[tool.ruff.isort]
known-first-party = ["stac_fastapi"]
known-third-party = ["stac_pydantic", "fastapi"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.black]
target-version = ["py38", "py39", "py310", "py311"]
