[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    "docs/source/conf.py",
    "build",
    "dist"
]
ignore = []
line-length = 90
select = [
    "C9",
    "E",
    "F",
    "W",
]

[tool.isort]
profile = "black"
known_first_party = "stac_fastapi"
known_third_party = ["stac-pydantic", "fastapi"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
