name: stac-fastapi
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint code
        if: ${{ matrix.python-version == 3.8 }}
        run: |
          python -m pip install pre-commit
          pre-commit run --all-files

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install core package
        run: |
          pip install .[dev]

      - name: Run test suite
        run: |
          pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing

  test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test generating docs
        run: make docs
