name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      # Rebuild website when docs have changed or code has changed
      - 'README.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - '**.py'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install mkdocs mkdocs-material pdocs

      - name: update API docs
        run: |
          pdocs as_markdown \
            --output_dir docs/api/ \
            --exclude_source \
            --overwrite \
            stac_fastapi

      - name: Deploy docs
        run: mkdocs gh-deploy --force
